; Exercise 1.38. In 1737, the Swiss mathematician Leonhard Euler
; published a memoir De Fractionibus Continuis,
; which included a continued fraction expansion for e - 2,
; where e is the base of the natural logarithms.
; In this fraction, the Ni are all 1, and the Di are
; successively 1, 2, 1, 1, 4, 1, 1, 6, 1, 1, 8, ....
; Write a program that uses your cont-frac procedure from
; exercise 1.37 to approximate e, based on Euler's expansion.

; SOLUTION:

(define (cont-frac n d k)
    ((define (frac i) 
        (if (< i k)
            (/ (n i) (+ (d i) (frac (+ i 1))))
            (/ (n i) (d i))))
    (frac 1)))

; approximate e using cont-frac
; according to Euler's publication from 1737
; where e can be definde as continued fraction for e - 2
; where all ni -> 1 an di ->  1, 2, 1, 1, 4, 1, 1, 6, 1, 1, 8,...
; we can postulate that for each index i
; d(i) = 2(i + 1)/3
; because indices of non-1 values are 2, 5, 8, 11, 14, 17...
; all of those are 1 less than multiple of 3
; which is 3i - 1 (i.e. sequence of those indices is generated by the rule  3i - 1)
; thus base case is that if index plus 1 divided by 3 has reminder, then value of d(i) = 1
; otherwise, value of d(i) = 2(i + 1) / 3

(define (d i)
   (if (not (= 0 (remainder (+ i 1) 3)))
       1
       (* 2 (/ (+ i 1) 3))))

(define e
   (+ 2 (cont-frac (lambda (i) 1.0) d 10)))

e
;2.7182817182817183